# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
weight = 1
url = "/"
[main.params]
icon = "home"
newtab = false

[[main]]
identifier = "RSS"
name = "RSS"
weight = 2
url = "/index.xml"
[main.params]
icon = "RSS"
newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/niwanowa"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/niwa_nowa"

[social.params]
icon = "brand-x"
